# Project information
site_name: farwmarth’s note
site_author: 'farwmarth'
site_url: 'http://learndocs.farwmarth.com'

# Repository
# repo_name: 'GitHub'
# repo_url: 'https://github.com/wujiyu115/learndocs'

# Copyright
copyright: 'Copyright (c) 2016 farwmarth'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'
# theme: 'cinder'

extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  author:
    github: 'wujiyu115'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages:
- Home: 'index.md'
- 数据结构与算法:
    - '排序算法介绍': 'data_algorithms/algorithms1_intro.md'
- c++基础:
    - 'c++环境搭建(Win)': 'cplus/cplus_win.md'
    - '基础语法': 'cplus/cplus1_grammer.md'
    - '类': 'cplus/cplus2_class.md'
    - '内存分配': 'cplus/cplus3_memory.md'
    - '编译过程': 'cplus/cplus4_complier.md'
    - '常量修饰符': 'cplus/cplus5_const.md'
- python:
    - '语言简介': 'python/py1_intro.md'
    - '数据类型': 'python/py2_data.md'
    - '控制流程': 'python/py3_controller.md'
    - '函数': 'python/py4_func.md'
    - '步骤': 'python/py5_step.md'
    - '组织': 'python/py6_organize.md'
    - '类': 'python/py_class.md'
    - '变量作用域': 'python/py_scope.md'
    - '枚举': 'python/py_enum.md'
    - '异常捕捉': 'python/py_error.md'
    - '调试': 'python/py_test.md'
    - '文件io': 'python/py_fileio.md'
    - '模块': 'python/py_inmodule.md'
    - '网络库': 'python/py_urllib.md'
    - '模块管理': 'python/py_module_manager.md'
    - '线程': 'python/py_thread.md'
    - '协程': 'python/py_coroutine.md'
    - '图形界面编程': 'python/py_gui.md'
    - 'python2/3对比': 'python/py_diff2.md'
    - '常用库': 'python/py_modules.md'
    - 'pyqt使用': 'python/py_qt.md'
    - 'tornado': 'python/py_tornado.md'
    - '爬虫': 'python/py_spider.md'
    - '消息队列': 'python/py_mq.md'
- lua:
    - '数据类型': 'lua/lua1_data.md'
- swift:
    - 'swift基础入门': 'swift/swift1_intro.md'
- php:
    - '基础介绍': 'php/php1_intro.md'
- Atom编辑器:
    - 'atom': 'ide/atom.md'
    - '新手入门':
        - '为什么选择Atom？': 'ide/atom/1.1-Why-Atom.md'
        - '安装Atom': 'ide/atom/1.2-Installing-Atom.md'
        - 'Atom基础': 'ide/atom/1.3-Atom-Basics.md'
        - '小结': 'ide/atom/1.4-Summary.md'
    - '使用Atom':
        - 'Atom中的包': 'ide/atom/2.1-Atom-Packages.md'
        - '在Atom中移动': 'ide/atom/2.2-Moving-in-Atom.md'
        - '文本选择': 'ide/atom/2.3-Atom-Selections.md'
        - '编辑和删除文本': 'ide/atom/2.4-Editing-and-Deleting-Text.md'
        - '查找和替换': 'ide/atom/2.5-Find-and-Replace.md'
        - '代码段': 'ide/atom/2.6-Snippets.md'
        - '自动补全': 'ide/atom/2.7-Autocomplete.md'
        - '折叠': 'ide/atom/2.8-Folding.md'
        - '面板': 'ide/atom/2.9-Panes.md'
        - '语法': 'ide/atom/2.10-Grammar.md'
        - 'Atom中的版本控制': 'ide/atom/2.11-Version-Control-in-Atom.md'
        - '在Atom中写作': 'ide/atom/2.12-Writing-in-Atom.md'
        - '基本的自定义': 'ide/atom/2.13-Basic-Customization.md'
        - '小结': 'ide/atom/2.14-Summary.md'
    - 'Hacking Atom':
        - '所需工具': 'ide/atom/3.1-Tools-of-the-Trade.md'
        - '初始文件': 'ide/atom/3.2-The-Init-File.md'
        - '字数统计包': 'ide/atom/3.3-Package-Word-Count.md'
        - '文本处理包': 'ide/atom/3.4-Package-Modifying-Text.md'
        - '创建主题': 'ide/atom/3.5-Creating-a-Theme.md'
        - '图标': 'ide/atom/3.6-Iconography.md'
        - '调试': 'ide/atom/3.7-Debugging.md'
        - '编写 spec': 'ide/atom/3.8-Writing-specs.md'
        - '从Textmate中转换': 'ide/atom/3.9-Converting-from-TextMate.md'
    - '在Atom背后':
        - '配置API': 'ide/atom/4.1-Configuration-API.md'
        - '深入键表（keymap）': 'ide/atom/4.2-Keymaps-In-Depth.md'
        - '作用域设置、作用域和作用域描述符': 'ide/atom/4.3-Scoped-Settings-Scopes-and-Scope-Descriptors.md'
        - 'Atom中的序列化': 'ide/atom/4.4-Serialization-in-Atom.md'
        - '开发Node模块': 'ide/atom/4.5-Developing-Node-Modules.md'
        - '通过服务和其它包交互': 'ide/atom/4.6-Interacting-With-Other-Packages-Via-Services.md'
        - '维护你的包': 'ide/atom/4.7-Maintaining-Your-Packages.md'
        - '小结': 'ide/atom/4.8-Summary.md'
- Sublime Text编辑器:
    - 'sublimetext': 'ide/sublimetext.md'